function tauVec = JointSpaceInvdynCtrl(thetaVec, dthetaVec, eint, g, ...
                                  Mlist, Glist, Slist, thetaVecd, ...
                                  dthetaVecd, ddthetaVecd, Kp, Ki, Kd)
                              
% This function is for the realisation of a position controller 
% in joint space with inverdynamic model                        

e = thetaVecd - thetaVec;
tauVec ...
= MassMatrix(thetalist, Mlist, Glist, Slist) ...
  * (Kp * e + Ki * (eint + e) + Kd * (dthetaVecd - dthetaVec)) ...
  + InverseDynamics(thetaVec, dthetaVec, ddthetaVecd, g, ...
                    zeros(6, 1), Mlist, Glist, Slist);


end