function plotcoord(origin, xaxis, yaxis, zaxis, ax)

ld = 5;

plot3(ax, [origin(1), origin(1) + 0.1*xaxis(1)],...
    [origin(2), origin(2) + 0.1*xaxis(2)],...
    [origin(3), origin(3) + 0.1*xaxis(3)],'r','LineWidth',ld);
plot3(ax, [origin(1), origin(1) + 0.1*yaxis(1)],...
    [origin(2), origin(2) + 0.1*yaxis(2)],...
    [origin(3), origin(3) + 0.1*yaxis(3)],'b','LineWidth',ld);
plot3(ax, [origin(1), origin(1) + 0.1*zaxis(1)],...
    [origin(2), origin(2) + 0.1*zaxis(2)],...
    [origin(3), origin(3) + 0.1*zaxis(3)],'g','LineWidth',ld);

end